In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('/content/country_ai_index_dirty.csv')

In [18]:
df.head()

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
0,USA,North America,72596.06,92.1,87.14,Moderate,19952,417.69
1,Canada,north america,55834.08,96.78,84.67,Moderate,4233,393.62
2,germany,Europe,54777.23,91.98,85.01,Strict,6475,369.58
3,United Kingdom,Europe,52827.64,91.41,83.85,Moderate,5612,345.98
4,France,EUROPE,47719.02,92.23,83.46,Moderate,4722,353.71

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     32 non-null     object
 1   region                      32 non-null     object
 2   gdp_per_capita              32 non-null     object
 3   internet_penetration        31 non-null     object
 4   digital_maturity_index      31 non-null     float64
 5   country_ai_policy           32 non-null     object
 6   ai_patent_filings_2024      32 non-null     object
 7   ai_researchers_per_million  31 non-null     object
dtypes: float64(1), object(7)
memory usage: 2.1+ KB

In [20]:
df.isnull().sum()

country                       0
region                        0
gdp_per_capita                0
internet_penetration          1
digital_maturity_index        1
country_ai_policy             0
ai_patent_filings_2024        0
ai_researchers_per_million    1
dtype: int64

In [21]:
df[df.isnull().any(axis=1)]

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
6,Sweden,Europe,62895.06,NaN,89.87,Strict,2648,459.49
7,Spain,Europe,42920.92,87.06,NaN,Moderate,2266,289.09
9,Poland,Europe,26651.07,88.3,70.84,Moderate,1823,NaN

In [22]:
df["internet_penetration"].unique()

array(['92.1', '96.78', '91.98', '91.41', '92.23', '93.17', nan, '87.06',
       '86.01', '88.3', '61.11', '75.26%', '91.83', '95.55', '93.78',
       '68.92', '71.31', '81.59', '68.52', '85.36', '854.9', '81.42',
       '86.98', '76.92', '76.55', '56.4', '63.74', '71.54', '94.5',
       '94.46'], dtype=object)

In [23]:
df["internet_penetration"] = df["internet_penetration"].astype(str).str.replace("%", "", regex=False)

In [24]:
df["internet_penetration"] = pd.to_numeric(df["internet_penetration"], errors="coerce")

In [25]:
df["internet_penetration"].dtype

dtype('float64')

In [26]:
df["internet_penetration"].median()

87.06

In [27]:
df["internet_penetration"] = df["internet_penetration"].fillna(87.68)

In [28]:
df["internet_penetration"].isnull().sum()

np.int64(0)

In [29]:
df["digital_maturity_index"].median()

76.66

In [30]:
df["digital_maturity_index"] = df["digital_maturity_index"].fillna(76.66)

In [31]:
df["digital_maturity_index"].isnull().sum()

np.int64(0)

In [32]:
df["ai_researchers_per_million"].unique()

array(['417.69', '393.62', '369.58', '345.98', '353.71', '419.02',
       '459.49', '289.09', '296.83', nan, '147.04', '336.29', '368.11',
       '413 researchers', '501.2', '113.96', '91.39', '150.82', '77.25',
       '175.68', '148.97', '158.6', '140.6', '116.14', '119.76', '55.23',
       '82.73', '110.69', '390.71', '382.22'], dtype=object)

In [33]:
df["ai_researchers_per_million"] = df["ai_researchers_per_million"].str.replace(" researchers", "")

In [34]:
df["ai_researchers_per_million"] = pd.to_numeric(df["ai_researchers_per_million"])

In [35]:
df["ai_researchers_per_million"].median()

289.09

In [36]:
df["ai_researchers_per_million"] = df["ai_researchers_per_million"].fillna(289.09)

In [37]:
df["ai_researchers_per_million"].isnull().sum()

np.int64(0)

In [38]:
df.isnull().sum()

country                       0
region                        0
gdp_per_capita                0
internet_penetration          0
digital_maturity_index        0
country_ai_policy             0
ai_patent_filings_2024        0
ai_researchers_per_million    0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(1)

In [40]:
df=df.drop_duplicates()

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     31 non-null     object
 1   region                      31 non-null     object
 2   gdp_per_capita              31 non-null     object
 3   internet_penetration        31 non-null     float64
 4   digital_maturity_index      31 non-null     float64
 5   country_ai_policy           31 non-null     object
 6   ai_patent_filings_2024      31 non-null     object
 7   ai_researchers_per_million  31 non-null     float64
dtypes: float64(3), object(5)
memory usage: 2.2+ KB

In [43]:
df["ai_patent_filings_2024"].unique()

array(['19952', '4233', '6475', '5612', '4722', '2858', '2648', '2266',
       '2234', '1823', '2253', '17037', '7,081', '6422', '2218', '1161',
       '980', '1254', '703', '1145', '1362', '985', '-874', '665', '500',
       '240', '191', '272', '3270', '1801'], dtype=object)

In [44]:
df["ai_patent_filings_2024"] = pd.to_numeric(df["ai_patent_filings_2024"], errors="coerce")

In [45]:
df["ai_patent_filings_2024"].dtype

dtype('float64')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     31 non-null     object
 1   region                      31 non-null     object
 2   gdp_per_capita              31 non-null     object
 3   internet_penetration        31 non-null     float64
 4   digital_maturity_index      31 non-null     float64
 5   country_ai_policy           31 non-null     object
 6   ai_patent_filings_2024      30 non-null     float64
 7   ai_researchers_per_million  31 non-null     float64
dtypes: float64(4), object(4)
memory usage: 2.2+ KB

In [47]:
df["ai_patent_filings_2024"].median()

1812.0

In [48]:
df["ai_patent_filings_2024"] = df["ai_patent_filings_2024"].fillna(1812.0)

In [49]:
df.isnull().sum()

country                       0
region                        0
gdp_per_capita                0
internet_penetration          0
digital_maturity_index        0
country_ai_policy             0
ai_patent_filings_2024        0
ai_researchers_per_million    0
dtype: int64

In [50]:
df.to_csv("cleaned_country_ai_index.csv", index=False)

In [51]:
numeric_cols = df.select_dtypes(include="number").columns
numeric_cols

Index(['internet_penetration', 'digital_maturity_index',
       'ai_patent_filings_2024', 'ai_researchers_per_million'],
      dtype='object')

In [52]:
Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)

print("Q1:")
print(Q1)

print("Q3:")
print(Q3)

Q1:
internet_penetration           75.905
digital_maturity_index         70.440
ai_patent_filings_2024        982.500
ai_researchers_per_million    130.180
Name: 0.25, dtype: float64
Q3:
internet_penetration            92.70
digital_maturity_index          87.21
ai_patent_filings_2024        3064.00
ai_researchers_per_million     375.90
Name: 0.75, dtype: float64

In [53]:
IQR = Q3 - Q1
print(IQR)

internet_penetration            16.795
digital_maturity_index          16.770
ai_patent_filings_2024        2081.500
ai_researchers_per_million     245.720
dtype: float64

In [54]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = ((df[numeric_cols] < lower) | (df[numeric_cols] > upper))

print(outliers.sum())

internet_penetration          2
digital_maturity_index        1
ai_patent_filings_2024        4
ai_researchers_per_million    0
dtype: int64

In [55]:
outlier_rows = df[outliers.any(axis=1)]
outlier_rows

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
0,USA,North America,72596.06,92.10,87.14,Moderate,19952.0,417.69
2,germany,Europe,54777.23,91.98,85.01,Strict,6475.0,369.58
11,China,Asia,12441.12,75.26,85.77,Strict,17037.0,336.29
13,South Korea,Asia,42704.06,95.55,92.82,Strict,6422.0,413.00
20,Brazil,South America,17758.78,854.90,71.60,Moderate,1362.0,148.97
23,Colombia,South America,12290.3,76.92,670.70,Lenient,665.0,116.14
31,Brazil,south america,17758.78,854.90,71.60,Moderate,1362.0,148.97

In [56]:
for col in numeric_cols:
    print(col)
    print(df.loc[outliers[col], ["country", col]])

internet_penetration
    country  internet_penetration
20   Brazil                 854.9
31  Brazil                  854.9
digital_maturity_index
     country  digital_maturity_index
23  Colombia                   670.7
ai_patent_filings_2024
        country  ai_patent_filings_2024
0          USA                  19952.0
2       germany                  6475.0
11        China                 17037.0
13  South Korea                  6422.0
ai_researchers_per_million
Empty DataFrame
Columns: [country, ai_researchers_per_million]
Index: []